#include "nsISupports.idl"

[scriptable, uuid(4e3a2d20-a474-11dd-ad8b-0800200c9a66)]
interface nsIUbiquity : nsISupports
{
  void flagSystemFilenamePrefix(in string filenamePrefix,
                                in boolean wantNativeWrappers);

  void evalInSandbox(in AString source,
                     in string filename,
                     in long lineNo,
                     in string jsVersion
                     /* Sandbox param */);
};
