#include "nsISupports.idl"

[scriptable, uuid(4e3a2d20-a474-11dd-ad8b-0800200c9a66)]
interface nsIUbiquity : nsISupports
{
  long add(in long a, in long b);
  void throwArg(/* optional param */);
  void evalInSandbox(in AString source,
                     in string filename,
                     in long lineNo
                     /* Sandbox param */);
};
