if(typeof bespin==="undefined")bespin={};if(typeof document!=="undefined"){var link=document.getElementById("bespin_base");if(link){var href=link.href;bespin.base=href.substring(href.length-1)!=="/"?href+"/":href}else bespin.base=""}
(function(){if("undefined"===typeof A)var A=function(){function k(z,s){y.push({m:z,a:s})}var y=[],F={isBootstrap:true,queue:y,register:function(z,s){if(z.match(/^tiki/)&&this.ENV)if(this.ENV.app==="tiki"&&this.ENV.mode==="test"){if(!s.dependencies)s.dependencies={};s.dependencies.core_test="~"}k("register",arguments);return this},module:function(z,s){if(z.match(/\:tiki$/))this.tikiFactory=s;k("module",arguments);return this},start:function(){var z={};this.tikiFactory(null,z,null);z=z.Browser.start(this.ENV,
this.ARGS,y);y=null;return z}};if("undefined"!==typeof ENV)F.ENV=ENV;if("undefined"!==typeof ARGV)F.ARGS=ARGV;if("undefined"!==typeof ARGS)F.ARGS=ARGS;return F}();A.register("::tiki/1.0.0",{name:"tiki",version:"1.0.0"});A.module("::tiki/1.0.0:tiki",function(k,y){var F=/^::/,z=function(a){return!!F.exec(a)},s=function(){y.debug.apply(this,arguments)};y.debug=function(){var a=Array.prototype.join.call(arguments,"");k("sys").debug(a)};var h;h=Array.isArray?Array.isArray:function(a){if("object"!==typeof a)return false;
if(a instanceof Array)return true;return a.constructor&&a.constructor.name==="Array"};y.isArray=h;var o;if(Object.create)o=Object.create;else{var r=function(){},D=r.prototype;o=function(a){if(!a)a=Object.prototype;r.prototype=a;var b=new r;b.prototype=a;r.prototype=D;return b}}y.createObject=o;var t,w,f;t=function(){return function(){return this.init?this.init.apply(this,arguments):this}};w=function(){return f(this)};f=function(a){var b=t();b.prototype=o(a.prototype);b.prototype.constructor=b;b.super_=
a;b.extend=w;return b};y.extend=f;var i=function(a,b){if(b&&!b.displayName)b.displayName="parallel#fn";return function(c){if(a.length===0)return c(null,[]);var d=a.length,l=d,m=false,x,C=function(G){if(!m){if(G){m=true;return c(G)}--l<=0&&c()}};C.displayName="parallel#tail";for(x=0;x<d;x++)b(a[x],C)}};i.displayName="parallel";var n;n=Array.prototype.map?function(a,b){return a.map(b)}:function(a,b){var c,d=a.length,l=[];for(c=0;c<d;c++)l[c]=b(a[c],c);return l};n.displayName="map";var u=function(a,
b){var c="pending",d=[],l=false,m=null,x=function(C){b||(b=this);switch(c){case "ready":C.apply(null,m);break;case "running":d.push(C);break;case "pending":d.push(C);c="running";a.call(b,function(){m=Array.prototype.slice.call(arguments);var G=d,J=m;if(l){c="pending";d=[];m=null;l=false}else{c="ready";d=null}G&&G.forEach(function(M){M.apply(null,J)})});break}return this};x.displayName="once#handler";x.reset=function(){switch(c){case "ready":c="pending";d=[];m=null;break;case "running":l=true;break}};
x.reset.displayName="once#handler.reset";return x};y.once=u;var v=function(a,b){var c,d;for(c in a)if(a.hasOwnProperty(c)){d=a[c];if("function"===typeof d)if(!d.displayName){d.displayName=b?b+"."+c:c;v(d.prototype,d.displayName)}}return a},B=f(Error);B.prototype.init=function(a,b){a=a+" not found";if(b)a="string"===typeof b?a+" "+b:a+" in package "+(b.id||"(unknown)");this.message=a;return this};y.NotFound=B;var L=f(Error);L.prototype.init=function(a,b){if("undefined"!==typeof JSON)a=JSON.stringify(a);
this.message="Invalid package definition. "+b+" "+a};y.InvalidPackageDef=L;var K=function(){var a=function(d){return d.charCodeAt(0)<=32},b=function(d){d=d.charCodeAt(0);return d>=48&&d<=57},c=function(d,l){for(var m=0,x=0,C=0,G,J;;x++,C++){G=d.charAt(x);J=l.charAt(C);if(!b(G)&&!b(J))return m;else if(b(G))if(b(J)){if(G<J)if(m===0)m=-1;else if(G>J)if(m===0)m=+1;else if(G===0&&J===0)return m}else return+1;else return-1}};return function(d,l){for(var m=0,x=0,C=0,G=0,J,M,W;;){C=G=0;J=d.charAt(m);for(M=
l.charAt(x);a(J)||J=="0";){if(J=="0")C++;else C=0;J=d.charAt(++m)}for(;a(M)||M=="0";){if(M=="0")G++;else G=0;M=l.charAt(++x)}if(b(J)&&b(M))if((W=c(d.substring(m),l.substring(x)))!==0)return W;if(J===0&&M===0)return C-G;if(J<M)return-1;else if(J>M)return+1;++m;++x}}}();y.natcompare=K;var N=function(a){return new Error(""+a+" is an invalid version string")};N.displayName="invalidVers";var T=function(a,b,c,d){c=Number(c);d=Number(d);if(isNaN(c))throw N(a);if(isNaN(d))throw N(b);return c-d};T.displayName=
"compareNum";var g,I={parse:function(a){a=a.match(/^(=|~)?([\d]+?)(\.([\d]+?)(\.(.+))?)?$/);if(!a)return null;return[a,a[2],a[4]||"0",a[6]||"0",a[1]]},major:function(a){return Number(g(a)[1])},minor:function(a){return Number(g(a)[2])},patch:function(a){a=g(a)[3];return isNaN(Number(a))?a:Number(a)},STRICT:"strict",NORMAL:"normal",mode:function(a){return g(a)[4]==="="?I.STRICT:I.NORMAL},comparePatch:function(a,b){var c,d;if(a===b)return 0;c=Number(a);d=Number(b);return isNaN(c)?isNaN(d)?K(a,b):-1:
isNaN(d)?1:c<d?-1:c>d?1:0},compare:function(a,b){var c;if(a===b)return 0;if(a)a=g(a);if(b)b=g(b);if(!a&&!b)return 0;if(!a)return-1;if(!b)return 1;c=T(a[0],b[0],a[1],b[1]);if(c===0){c=T(a[0],b[0],a[2],b[2]);if(c===0)c=I.comparePatch(a[3],b[3])}return c<0?-1:c>0?1:0},compatible:function(a,b){if(!a)return true;if(a===b)return true;if(a&&!g(a))a=null;if(b&&!g(b))b=null;if(!a)return true;if(a===b)return true;if(I.mode(a)===I.STRICT)return b&&I.compare(a,b)===0;else{if(!b)return true;if(I.major(a)!==I.major(b))return false;
return I.compare(a,b)<=0}},normalize:function(a){var b;if(!a||a.length===0)return null;a=I.parse(a);if(!a)return null;b=Number(a[3]);if(isNaN(b))b=a[3];return[Number(a[1]),Number(a[2]),b].join(".")}};y.semver=I;g=I.parse;var Q=y.extend(Object);y.Factory=Q;Q.prototype.init=function(a,b,c){this.id=a;this.pkg=b;this.factory=c};Q.prototype.call=function(a,b){var c=this.factory,d=this.__filename,l=this.__dirname;if("string"===typeof c)c=this.factory=Q.compile(c,this.pkg.id+":"+this.id);a=a.createRequire(b);
var m=b.exports;c.call(m,a,m,b,d,l);return b.exports};var U=["(function(require, exports, module) {",null,"\n});\n//@ sourceURL=",null,"\n"];Q.compile=function(a,b){U[1]=a;U[3]=b||"(unknown module)";a=U.join("");a=eval(a);U[1]=U[3]=null;return a};y.Factory=Q;var R=y.extend(Object);y.Module=R;R.prototype.init=function(a,b,c){this.id=a;this.ownerPackage=b;this.exports={};var d=this;this.resource=function(l){return c.resource(l,d.id,b)}};var P=y.extend(Object);y.Package=P;P.prototype.init=function(a,
b){z(a)||(a="::"+a);this.id=a;this.config=b;this.isReady=true};P.prototype.get=function(a){return this.config?this.config[a]:undefined};P.prototype.set=function(a,b){if(!this.config)this.config={};this.config[a]=b;return this};P.prototype.requiredVersion=function(a){var b=this.get("dependencies");return b?b[a]:null};P.prototype.canonicalPackageId=function(a,b){if(a===this.get("name")&&I.compatible(b,this.get("version")))return this.id;return null};P.prototype.packageFor=function(a){if(a===this.id)return this;
return null};P.prototype.ensurePackage=function(a,b){return a===this.id?b():b(new B(a,this))};P.prototype.catalogPackages=function(){return[this]};P.prototype.exists=function(a){return!!(this.factories&&this.factories[a])};P.prototype.load=function(a){return this.factories?this.factories[a]:null};var e=function(a,b){return a+":"+b},j=y.extend(Object);y.Loader=j;j.prototype.init=function(a){this.sources=a||[];this.clear()};j.prototype.clear=function(){this.factories={};this.canonicalIds={};this.packages=
{};this.packageSources={};this.canonicalPackageIds={}};j.prototype.defaultPackage=new P("default",{name:"default"});j.prototype.anonymousPackage=new P("(anonymous)",{name:"(anonymous)"});j.prototype.canonical=function(a,b,c){var d,l,m,x;if(b&&"string"!==typeof b){c=b;b=null}if(z(a))return a;if(!c)c=this.anonymousPackage;a=this._resolve(a,b,c);if(z(a))return a;d=c?c.id:"(null)";b=this.canonicalIds;if(!b)b=this.canonicalIds={};b[d]||(b[d]={});b=b[d];if(b[a])return b[a];d=a;l=a.indexOf(":");if(l>=0){m=
a.slice(0,l);a=a.slice(l+1);if(a[0]==="/")throw new Error("Absolute path not allowed with packageId");}l=null;if(m&&m.length>0){if(m=this._canonicalPackageId(m,null,c))l=e(m,a)}else{if(c&&c.exists(a))l=e(c.id,a);else{if(m=this._canonicalPackageId(a,null,c))x=this._packageFor(m,c);if(x)if(x.exists("index"))l=e(x.id,"index");else if(x.exists(a))l=e(x.id,a)}if(!l){if(this.defaultPackage)m=this.defaultPackage.id;else if(this.workingPackage)m=this.workingPackage.id;else if(this.anonymousPackage)m=this.anonymousPackage.id;
else return null;if(m)l=e(m,a)}}return b[d]=l};j.prototype.load=function(a,b,c){var d,l,m;if(!b)b=this.anonymousPackage;d=this.factories;if(!d)d=this.factories={};if(d[a])return d[a];l=a.indexOf(":",2);m=a.slice(0,l);l=a.slice(l+1);(b=this._packageFor(m,b))||s("Loader#load - "+m+" not found for "+l);if(!b)return null;c=b.load(l,c);return d[a]=c};j.prototype.catalogPackages=function(a){if(!a)a=this.anonymousPackage;var b=[],c,d,l={};this.defaultPackage&&b.push(this.defaultPackage);var m=function(x){var C,
G,J,M;if(x){G=x.length;for(C=0;C<G;C++){M=x[C];(J=l[M.get("name")])||(J=l[M.get("name")]={});if(!J[M.get("version")]){b.push(M);J[M.get("version")]=M}}}};a&&m(a.catalogPackages());a=this.sources;d=a.length;for(c=0;c<d;c++)m(a[c].catalogPackages());l=null;return b};j.prototype.canonicalPackageId=function(a,b,c){var d;if(a instanceof P)return a.id;if(z(a)){d=a.indexOf(":",2);if(d>=0)a=a.slice(0,d);return a}if(b&&"string"!==typeof b){c=b;b=null}if(!c)c=this.anonymousPackage;d=a.indexOf(":");if(d>=0)a=
a.slice(0,d);return this._canonicalPackageId(a,b,c)};j.prototype.packageFor=function(a,b){if(!b)b=this.anonymousPackage;var c=a.indexOf(":",2);if(c>=0)a=a.slice(0,c);return this._packageFor(a,b)};j.prototype.ready=function(a,b){if(!b)b=this.anonymousPackage;var c=a.indexOf(":",2),d;if(c>=0){d=a.slice(c+1);a=a.slice(0,c)}if(this._packageReady(a,b,{})){a=this._packageFor(a,b);if(!a)return false;return!!a.exists(d)}else return false};j.prototype.ensurePackage=function(a,b,c,d){if(b&&"string"!==typeof b){d=
c;c=b;b=null}if(c&&"function"===typeof c){d=c;c=null}if(!c)c=this.anonymousPackage;this._ensurePackage(a,b,c,{},d)};j.prototype._ensurePackage=function(a,b,c,d,l){var m=this,x;x=this._canonicalPackageId(a,b,c);if(!x)return l(new B(a,c));if(d[x])return l();d[x]=true;a=this._sourceForCanonicalPackageId(x,c);if(!a)return l(new B(x,c));a.ensurePackage(x,function(C){var G,J,M;if(C)return l(C);G=m.packageFor(x,c);if(!G)return l(new B(x,c));C=G.get("dependencies");if(!C)return l();M=[];for(J in C)C.hasOwnProperty(J)&&
M.push({packageId:J,vers:C[J]});i(M,function(W,V){m._ensurePackage(W.packageId,W.vers,G,d,V)})(l)})};j.prototype._canonicalPackageId=function(a,b,c){if(a instanceof P)return a.id;if(z(a))return a;if(a==="default"&&this.defaultPackage)return this.defaultPackage.id;var d=this.canonicalPackageIds,l,m,x,C,G;if(!c)c=this.anonymousPackage;if(!c)throw new Error("working package is required");b||(b=c.requiredVersion(a));l=c.id;if(!d)d=this.canonicalPackageIds={};d[l]||(d[l]={});d=d[l];d[a]||(d[a]={});d=d[a];
if(d[b])return d[b];l=this.sources;m=c.canonicalPackageId(a,b);G=c;if(!m)if(m=c.canonicalPackageId(a,null))throw new Error(c.get("name")+" contains an incompatible nested package "+a+" (expected: "+b+")");if(!m&&l){C=l.length;for(x=0;!m&&x<C;x++){G=l[x];m=G.canonicalPackageId(a,b)}}m&&this._cachePackageSource(m,c,G);return d[b]=m};j.prototype._cachePackageSource=function(a,b,c){var d=this.packageSources;b=b.id;if(!d)d=this.packageSources={};d[b]||(d[b]={});d=d[b];d[a]=c};j.prototype._sourceForCanonicalPackageId=
function(a,b){var c=this.packageSources,d=b.id,l,m;if(!c)c=this.packageSources={};c[d]||(c[d]={});c=c[d];if(c[a])return c[a];d=this.sources;if(b)if(l=b.packageFor(a))m=b;if(!m&&d){b=d.length;for(l=0;!m&&l<b;l++){m=d[l];m.packageFor(a)||(m=null)}}return c[a]=m};j.prototype._packageFor=function(a,b){var c,d;if(this.defaultPackage&&a===this.defaultPackage.id)return this.defaultPackage;c=this.packages;if(!c)c=this.packages={};if(c[a])return c[a];if(b=this._sourceForCanonicalPackageId(a,b))d=b.packageFor(a);
return c[a]=d};j.prototype._packageReady=function(a,b,c){var d;if(c[a])return true;c[a]=true;b=this._packageFor(a,b);if(!b)return false;a=b.get("dependencies");for(d in a)if(a.hasOwnProperty(d)){a=a[d];a=this._canonicalPackageId(d,a,b);if(!a)return false;return this._packageReady(a,b,c)}return true};j.prototype._resolve=function(a,b,c){var d,l,m,x;if(a[0]==="/"&&a.indexOf(":")<0)return this.anonymousPackage.id+":"+a;if(a.match(/(^\.\.?\/)|(\/\.\.?\/)|(\/\.\.?\/?$)/)){if((d=a.indexOf(":"))>=0){x=a.slice(0,
d);a=a.slice(d+1);b=[]}else if(a.match(/^\.\.?\//)){if(!b)throw new Error("id required to resolve relative id: "+a);if(b.indexOf(":")>=0)throw new Error("current moduleId cannot contain packageId");if(c)x=c.id;b=b.split("/");b.pop()}else b=[];m=a.split("/");c=m.length;for(d=0;d<c;d++){l=m[d];if(l===".."){if(b.length<1)throw new Error("invalid path: "+a);b.pop()}else l!=="."&&b.push(l)}a=b.join("/");if(x)a=e(x,a)}return a};var q=y.extend(Object);y.Sandbox=q;q.prototype.init=function(a,b,c,d){this.loader=
a;this.env=b;this.args=c;d&&this.main(d);this.clear()};q.prototype.catalogPackages=function(a){return this.loader.catalogPackages(a)};q.prototype.createRequire=function(a){var b=this,c=a.id,d=a.ownerPackage,l=function(m,x){if(x&&m.indexOf(":")<0){if(x.isPackage)x=x.id;m=x+":"+m}return b.require(m,c,d)};a=l.displayName=(c||"(unknown)")+"#require";l.nativeRequire=b.nativeRequire;l.ensure=function(m,x){if(!h(m)){m=Array.prototype.slice.call(arguments);x=m.pop()}i(m,function(C,G){b.ensure(C,c,d,G)})(function(C){if(C)return x(C);
if(x.length<=1)return x();x(null,n(m,function(G){return b.require(G,c,d)}))})};l.ensure.displayName=a+".ensure";l.ready=function(m){var x,C;h(m)||(m=Array.prototype.slice.call(arguments));C=m.length;for(x=0;x<C;x++)if(!b.ready(m[x],c,d))return false;return true};l.ready.displayName=a+".ready";l.packageFor=function(m,x){return b.packageFor(m,x,d)};l.packageFor.displayName=a+".packageFor";l.ensurePackage=function(m,x,C){b.ensurePackage(m,x,d,function(G){if(G)return C(G);if(C.length<=1)return C();C(null,
b.packageFor(m,x,d))})};l.ensurePackage.displayName=a+".ensurePackage.displayName";l.catalogPackages=function(){return b.catalogPackages(d)};l.main=b.main();l.env=b.env;l.args=b.args;l.sandbox=b;l.loader=b.loader;l.isTiki=true;return l};q.prototype.Module=R;q.prototype.module=function(a,b,c){var d,l,m;b=this.loader.canonical(a,b,c);if(!b)throw new B(a,c);d=this.modules;if(!d)d=this.modules={};if(a=d[b])return a;l=b.indexOf(":",2);a=b.slice(l+1);l=b.slice(0,l);m=this.loader.packageFor(l,c);if(!m)throw new B(l,
c);return a=d[b]=new this.Module(a,m,this)};q.prototype.main=function(a,b){if(a!==undefined){this._mainModule=null;this._mainModuleId=a;this._mainModuleWorkingPackage=b;return this}else{if(!this._mainModule&&this._mainModuleId){b=this._mainModuleWorkingPackage;this._mainModule=this.module(this._mainModuleId,b)}return this._mainModule}};q.prototype.require=function(a,b,c){var d,l;b=this.loader.canonical(a,b,c);if(!b)throw new B(a,c);l=this.exports;a=this.usedExports;if(!l)l=this.exports={};if(!a)a=
this.usedExports={};if(d=l[b]){d=d.exports;a[b]||(a[b]=d);return d}d=this.loader.load(b,c,this);if(!d)throw new B(b,c);c=this.module(b,c);l[b]=c;l=d.call(this,c);c.exports=l;if(a[b]&&a[b]!==l)throw new Error("cyclical requires() in "+b);return l};q.prototype.ready=function(a,b,c){return(a=this.loader.canonical(a,b,c))?this.loader.ready(a):false};q.prototype.ensure=function(a,b,c,d){var l,m,x;if(b&&"string"!==typeof b){d=c;c=b;b=null}if(c&&"function"===typeof c){d=c;c=null}b=this.loader.canonical(a,
b,c);if(!b)return d(new B(a,c));x=b.indexOf(":",2);a=b.slice(x+1);m=b.slice(0,x);l=this.loader;l.ensurePackage(m,c,function(C){if(C)return d(C);C=l.packageFor(m,c);C.exists(a)?d():d(new B(a,C))})};q.prototype.packageFor=function(a,b,c){a=this.loader.canonicalPackageId(a,b,c);if(!a)return null;return this.loader.packageFor(a)};q.prototype.ensurePackage=function(a,b,c,d){if(b&&"string"!==typeof b){d=c;c=b;b=null}if(c&&"function"===typeof c){d=c;c=null}b=this.loader.canonicalPackageId(a,b,c);if(!b)return d(new B(a,
c));this.loader.ensurePackage(b,d)};q.prototype.resource=function(a,b,c){if(!c.resource)return null;return c.resource(a,b)};q.prototype.clear=function(){this.exports={};this.modules={};this.usedExports={};return this};var p=y.extend(Object);y.Browser=p;p.prototype.init=function(){this._ready={};this._unload={};this.clear()};p.prototype.clear=function(){this.packageInfoByName={};this.packageInfoById={};this.packages={};this.factories={};this.stylesheetActions={};this.scriptActions={};this.ensureActions=
{}};p.start=function(a,b,c){var d;d=new p;d.loader=new j([d]);d.sandbox=new q(d.loader,a,b);d.queue=c;d.require=d.sandbox.createRequire({id:"index",ownerPackage:d.loader.anonymousPackage});return d};p.prototype.replay=function(){var a=this.queue,b=a?a.length:0,c,d;this.queue=null;for(c=0;c<b;c++){d=a[c];this[d.m].apply(this,d.a)}return this};p.prototype.start=function(){return this};p.prototype.global=function(a){if(!O&&!X)return this;var b=function(){return this}(),c,d,l,m,x,C,G,J;c=this.globals;
if(!c)c=this.globals={};d=this.packageFor(a);if(!d)throw new Error(a+" package not found");l=d.get("dependencies");if(!l)return this;for(m in l)if(l.hasOwnProperty(m)){a=this.loader.canonical(m,d);if(!c[a]){c[a]=true;if(this.sandbox.ready(m,d)){a=this.sandbox.require(m,d);if(x=a.__globals__){J=x.length;for(G=0;G<J;G++){C=x[G];b[C]=a[C]}}else for(C in a)if(a.hasOwnProperty(C))b[C]=a[C]}}}return this};var E=function(a){var b,c;if(a.length===1){b=null;c=a[0];a=Array.prototype.slice.call(a,1)}else{b=
a[0];c=a[1];a=Array.prototype.slice.call(a,2)}return{target:b,method:c,args:a}},H=function(a,b,c){a[b]||(a[b]=[]);a[b].push(E(c))};p.prototype.addReadyListener=function(){if(this._ready&&this._ready.isReady)this._invoke(E(arguments));else{this._setupReadyListener();H(this._ready,"queue",arguments)}};p.prototype.addMainListener=function(){if(this._ready&&this._ready.isReady)this._invoke(E(arguments));else{this._setupReadyListener();H(this._ready,"mqueue",arguments)}};p.prototype.addUnloadListener=
function(){if(this._unload&&this._unload.isUnloading)this._invoke(E(arguments));else{this._setupUnloadListener();H(this._unload,"queue",arguments)}};p.prototype._invoke=function(a){var b=a.target,c=a.method;if("string"===typeof b)b=this.require(b);if("string"===typeof c)c=b[c];c&&c.apply(b,a.args);a.target=a.method=a.args=null};p.prototype._setupReadyListener=function(){if(this._ready.setup)return this;this._ready.setup=true;var a=this._ready,b=this,c;c=function(){if(!a.isReady){a.isReady=true;a.cleanup&&
a.cleanup();a.cleanup=null;var d,l,m;l=(d=a.queue)?d.length:0;a.queue=null;for(m=0;m<l;m++)b._invoke(d[m]);l=(d=a.mqueue)?d.length:0;a.mqueue=null;for(m=0;m<l;m++)b._invoke(d[m]);b._runMain()}};if("undefined"!==typeof document)if(document.addEventListener){a.cleanup=function(){document.removeEventListener("DOMContentLoaded",c,false);document.removeEventListener("load",c,false)};document.addEventListener("DOMContentLoaded",c,false);document.addEventListener("load",c,false)}else if(document.attachEvent){a.cleanup=
function(){document.detachEvent("onreadystatechange",c);document.detachEvent("onload",c);a.ieHandler=null};document.attachEvent("onreadystatechange",c);document.attachEvent("onload",c);if(document.documentElement.doScroll&&window==window.top){a.ieHandler=function(){if(a.ieHandler&&!a.isReady)try{document.documentElement.doScroll("left")}catch(d){setTimeout(a.ieHandler,0);return}c()};a.ieHandler()}}};p._scheduleUnloadListener=function(){if(this._unload.setup)return this;this._unload.setup=true;var a=
this._unload,b=this,c;a.isUnloading=false;c=function(){if(!a.isUnloading){a.isUnloading=true;a.cleanup&&a.cleanup();a.cleanup=null;var d=a.queue,l=d?d.length:0,m;a.queue=null;for(m=0;m<l;m++)b._invoke(d[m])}};if("undefined"!==typeof document)if(document.addEventListener){a.cleanup=function(){document.removeEventListener("unload",c)};document.addEventListener("unload",c,false)}else if(document.attachEvent){a.cleanup=function(){document.detachEvent("onunload",c)};document.attachEvent("unload",c)}};
p.prototype.main=function(a,b){this.sandbox&&this.sandbox.main(a);this._setupReadyListener();this._main={id:a,method:b}};p.prototype._runMain=function(){if(this._main){var a=this._main.id,b=this._main.method,c=this.require;if(a&&c){this._main=null;c.ensure(a,function(d){if(d)throw d;d=c(a);if("string"===typeof b)b=d[b];b&&b.call(d)})}}};p.prototype._action=function(a){var b;return b=u(function(c){b.resolve=function(d,l){b.resolve=null;c(d,l)};a()})};p.prototype._resolve=function(a,b,c){if(a[b])a[b].resolve&&
a[b].resolve(null,c);else a[b]=function(d){d(null,c)};return this};p.prototype._fail=function(a,b,c){a[b].resolve&&a[b].resolve(c)};p.prototype._normalize=function(a,b){z(b)||(b="::"+b);a.id=b;a.version=I.normalize(a.version);a["tiki:external"]=!!a["tiki:external"];a["tiki:private"]=!!a["tiki:private"];var c=a["tiki:base"];if(a["tiki:resources"])a["tiki:resources"]=n(a["tiki:resources"],function(m){if("string"===typeof m)m={id:b+":"+m,name:m};if(!m.name)throw new L(a,"resources must have a name");
if(!m.id)m.id=b+":"+m.name;if(!z(m.id))m.id="::"+m.id;if(!m.type)m.type=m.name.match(/\.js$/)?"script":m.name.match(/\.css$/)?"stylesheet":"resource";if(!m.url)m.url=c?c+"/"+m.name:m.id+m.name;return m});if(!a.dependencies)a.dependencies={};var d=a["tiki:nested"],l;if(d)for(l in d){if(d.hasOwnProperty(l))z(d[l])||(d[l]="::"+d[l])}else a["tiki:nested"]={};return a};p.prototype.register=function(a,b){var c,d,l,m=-1;b=this._normalize(b,a);a=b.id;c=this.packageInfoById;if(!c)c=this.packageInfoById={};
if(c[a]){if(!c[a]["tiki:external"])return this;d=c[a]}c[a]=b;if(b.name){a=b.name;l=b.version;c=this.packageInfoByName;if(!c)c=this.packageInfoByName={};c[a]||(c[a]={});c=c[a];if(!c[l]||c[l].length<=1)c[l]=[b];else{if(d)m=c[l].indexOf(d);if(m>=0)c[l]=c[l].slice(0,m).concat(c[l].slice(m+1));c[l].push(b)}}return this};p.prototype.module=function(a,b){z(a)||(a="::"+a);this.factories[a]=b;return this};p.prototype.script=function(a){z(a)||(a="::"+a);this._resolve(this.scriptActions,a,true)};p.prototype.stylesheet=
function(a){z(a)||(a="::"+a);this._resolve(this.stylesheetActions,a,true)};var O="undefined"!==typeof document&&document.createElement,X="undefined"!==typeof XMLHttpRequest;p.prototype.xhr=!O;p.prototype.autowrap=false;var Z=function(a){if(!a)return null;for(var b=a.length;--b>=0;)if(!a[b]["tiki:private"])return a[b];return null};p.prototype.canonicalPackageId=function(a,b){a=this.packageInfoByName[a];var c,d,l;if(b)b=I.normalize(b);if(!a)return null;if(a[b]&&a[b].length===1)return a[b][0].id;for(d in a)if(a.hasOwnProperty(d))if(I.compatible(b,
d))if(!c||I.compare(l,d)<0)if(c=Z(a[d]))l=d;return c?c.id:null};p.prototype.packageFor=function(a){var b=this.packages[a];if(b)return b;if((b=this.packageInfoById[a])&&!b["tiki:external"]){b=new this.Package(a,b,this);return this.packages[a]=b}return null};p.prototype.ensurePackage=function(a,b){var c=this.ensureActions[a];if(c)return c(b);var d=this.packageInfoById[a];if(!d)return b(new B(a,"browser package info"));var l=this;c=u(function(m){var x=1,C=false,G,J=function(Y){if(!G){if(Y){G=true;return m(Y)}x-=
1;if(x<=0&&C)return m(null,d)}},M=d.dependencies,W=d["tiki:nested"],V,S;for(V in M)if(M.hasOwnProperty(V)){S=W[V];if(!S){S=M[V];S=l.canonicalPackageId(V,S)}if(S&&l.packageInfoById[a]){x++;l.ensurePackage(S,J)}}W=(M=d["tiki:resources"])?M.length:0;for(V=0;V<W;V++){S=M[V];if(S.type!=="resource")if(S.type==="script"){x++;l.ensureScript(S.id,S.url,J)}else if(S.type==="stylesheet"){x++;l.ensureStylesheet(S.id,S.url,J)}}C=true;J()});this.ensureActions[a]=c;c(b)};p.prototype.ensureScript=function(a,b,c){var d=
this.scriptActions[a];if(d)return d(c);var l=this;d=this._action(function(){l._loadScript(a,b)});this.scriptActions[a]=d;return d(c)};p.prototype.ensureStylesheet=function(a,b,c){var d=this.stylesheetActions[a];if(d)return d(c);var l=this;d=this._action(function(){l._loadStylesheet(a,b)});this.stylesheetActions[a]=d;return d(c)};p.prototype._injectScript=function(a,b){var c;a=document.body;c=document.createElement("script");c.src=b;a.appendChild(c)};p.prototype._xhrScript=function(a,b){var c=this.autowrap,
d=new XMLHttpRequest;d.open("GET",b,true);d.onreadystatechange=function(){if(!(d.readyState!==4||d.status!==200&&d.status!==0)){var l=d.responseText;if(c)l="tiki.module('"+a+"', function(require, exports, module) {"+l+"});tiki.script('"+a+"');";eval(l+"\n//@ sourceURL="+b)}};d.send(null)};p.prototype._loadScript=function(a,b){if(this.autowrap){this.xhr=true;X||s("Autowrap is on but XHR is not available. Danger ahead.")}if(X&&O)if(this.xhr)try{return this._xhrScript(a,b)}catch(c){return this._injectScript(a,
b)}else try{return this._injectScript(a,b)}catch(d){return this._xhrScript(a,b)}else if(X)return this._xhrScript(a,b);else if(O)return this._injectScript(a,b);s("Browser#_loadScript() not supported on this platform.");this.script(a)};p.prototype._loadStylesheet=O?function(a,b){var c,d;c=document.getElementsByTagName("head")[0]||document.body;d=document.createElement("link");d.rel="stylesheet";d.href=b;d.type="text/css";c.appendChild(d);this.stylesheet(a)}:function(a){s("Browser#_loadStylesheet() not supported on this platform.");
this.stylesheet(a)};R=P.extend();p.prototype.Package=R;R.prototype.init=function(a,b,c){P.prototype.init.call(this,a,b);this.source=c};R.prototype.canonicalPackageId=function(a,b){var c;if(c=P.prototype.canonicalPackageId.call(this,a,b))return c;c=(this.get("tiki:nested")||{})[a];if(!c)return null;return(a=this.source.packageInfoById[c])&&I.compatible(b,a.version)?c:null};R.prototype.packageFor=function(a){var b=P.prototype.packageFor.call(this,a);return b?b:this.source.packageFor(a)};R.prototype.ensurePackage=
function(a,b){if(a===this.id)return b();this.source.ensurePackage(a,b)};R.prototype.catalogPackages=function(){var a=[this],b,c;b=this.get("tiki:nested")||{};for(c in b)b.hasOwnProperty(c)&&a.push(this.source.packageFor(b[c]));return a};R.prototype.exists=function(a){return!!this.source.factories[this.id+":"+a]};R.prototype.load=function(a){var b;return(b=this.source.factories[this.id+":"+a])?new this.Factory(a,this,b):null};R.prototype.Factory=Q;v(y,"tiki")});A=A.start();A.replay();bespin.tiki=A})();
bespin.tiki.register("::jquery",{name:"jquery",dependencies:{}});bespin.tiki.module("jquery:index",function(A,k){k.$=window.$});bespin.tiki.register("::bespin",{name:"bespin",dependencies:{jquery:"0.0.0"}});bespin.bootLoaded=true;
bespin.tiki.module("bespin:builtins",function(A,k){k.metadata={bespin:{provides:[{ep:"extensionpoint",name:"extensionpoint",description:"Defines a new extension point",params:[{name:"name",type:"string",description:"the extension point's name",required:true},{name:"description",type:"string",description:"description of what the extension point is for"},{name:"params",type:"array of objects",description:"parameters that provide the metadata for a given extension. Each object should have name and description, minimally. It can also have a 'type' (eg string, pointer, or array) and required to denote whether or not this parameter must be present on the extension."},
{name:"indexOn",type:"string",description:"You can provide an 'indexOn' property to name a property of extensions through which you'd like to be able to easily look up the extension."},{name:"register",type:"pointer",description:"function that is called when a new extension is discovered. Note that this should be used sparingly, because it will cause your plugin to be loaded whenever a matching plugin appears."},{name:"unregister",type:"pointer",description:"function that is called when an extension is removed. Note that this should be used sparingly, because it will cause your plugin to be loaded whenever a matching plugin appears."}]},
{ep:"extensionpoint",name:"extensionhandler",description:"Used to attach listeners ",params:[{name:"name",type:"string",description:"name of the extension point to listen to",required:true},{name:"register",type:"pointer",description:"function that is called when a new extension is discovered. Note that this should be used sparingly, because it will cause your plugin to be loaded whenever a matching plugin appears."},{name:"unregister",type:"pointer",description:"function that is called when an extension is removed. Note that this should be used sparingly, because it will cause your plugin to be loaded whenever a matching plugin appears."}]},
{ep:"extensionpoint",name:"factory",description:"Provides a factory for singleton components. Each extension needs to provide a name, a pointer and an action. The action can be 'call' (if the pointer refers to a function), 'new' (if the pointer refers to a traditional JS object) or 'value' (if the pointer refers to the object itself that is the component).",indexOn:"name"},{ep:"factory",name:"hub",action:"create",pointer:"util/hub#Hub"},{ep:"extensionpoint",name:"command",description:"Editor commands/actions. TODO: list parameters here."}]}}});
bespin.tiki.module("bespin:console",function(A,k){A=A("util/util");var y=function(){},F=["assert","count","debug","dir","dirxml","error","group","groupEnd","info","log","profile","profileEnd","time","timeEnd","trace","warn"];if(typeof window==="undefined"){var z={};F.forEach(function(s){z[s]=function(){var h=Array.prototype.slice.call(arguments);postMessage(JSON.stringify({op:"log",method:s,args:h}))}});k.console=z}else if(A.isSafari||A.isChrome)k.console=window.console;else{k.console={};F.forEach(function(s){k.console[s]=
window.console&&window.console[s]?window.console[s]:y})}});
bespin.tiki.module("bespin:globals",function(){if(!Object.defineProperty)Object.defineProperty=function(A,k,y){var F=Object.prototype.hasOwnProperty;if(typeof y=="object"&&A.__defineGetter__){if(F.call(y,"value")){if(!A.__lookupGetter__(k)&&!A.__lookupSetter__(k))A[k]=y.value;if(F.call(y,"get")||F.call(y,"set"))throw new TypeError("Object doesn't support this action");}else typeof y.get=="function"&&A.__defineGetter__(k,y.get);typeof y.set=="function"&&A.__defineSetter__(k,y.set)}return A};if(!Object.defineProperties)Object.defineProperties=
function(A,k){for(var y in k)Object.prototype.hasOwnProperty.call(k,y)&&Object.defineProperty(A,y,k[y]);return A};(function(){if(!Array.isArray)Array.isArray=function(A){return A&&Object.prototype.toString.call(A)=="[object Array]"};if(!Object.keys)Object.keys=function(A){var k,y=[];for(k in A)A.hasOwnProperty(k)&&y.push(k);return y};if(!Function.prototype.bind)Function.prototype.bind=function(){var A=Array.prototype.slice.call(arguments),k=this,y=function(){return k.call.apply(k,A.concat(Array.prototype.slice.call(arguments)))};
y.name=this.name;y.displayName=this.displayName;y.length=this.length;y.unbound=k;return y}})()});bespin.tiki.module("bespin:index",function(A,k){k.versionNumber="tip";k.versionCodename="DEVELOPMENT MODE";k.apiVersion="dev"});
bespin.tiki.module("bespin:plugins",function(A,k){A("globals");var y=A("promise").Promise,F=A("promise").group,z=A("builtins"),s=A("console").console,h=A("util/util");A("util/stacktrace");var o=A.loader.sources[0],r=function(f,i){if(i){i=i.split("#");return{modName:i[0]?f+":"+i[0]:f,objName:i[1]}}},D=function(f){var i=A(f.modName);if(f.objName)return i[f.objName];return i};k.Extension=function(f){this.pluginName=null;for(property in f)if(f.hasOwnProperty(property))this[property]=f[property];this._observers=
[]};k.Extension.prototype={load:function(f,i){var n=new y,u=function(B){f&&f(B);n.resolve(B)};i=this[i||"pointer"];if(h.isFunction(i)){u(i);return n}var v=r(this.pluginName,i);if(!v){s.error("Extension cannot be loaded because it has no 'pointer'");s.log(this);n.reject(new Error("Extension has no 'pointer' to call"));return n}k.catalog.loadPlugin(this.pluginName).then(function(){A.ensure(v.modName,function(){var B=D(v);u(B)})});return n},observe:function(f,i,n){this._observers.push({plugin:f,callback:i,
property:n});this.load(i,n)},getPluginName:function(){return this.pluginName},_getLoaded:function(f){f=this._getPointer(f);return D(f)}};k.ExtensionPoint=function(f,i){this.name=f;this.catalog=i;this.indexOn=this.pluginName=undefined;this.extensions=[];this.handlers=[]};k.ExtensionPoint.prototype={getImplementingPlugins:function(){var f={};this.extensions.forEach(function(n){f[n.pluginName]=true});var i=Object.keys(f);i.sort();return i},getDefiningPluginName:function(){return this.pluginName},getByKey:function(f){var i=
this.indexOn;if(i)for(var n=0;n<this.extensions.length;n++)if(this.extensions[n][i]==f)return this.extensions[n]},register:function(f){this.extensions.push(f);this.handlers.forEach(function(i){i.register&&i.load(function(n){n?n(f):s.error("missing register function for pluginName=",f.pluginName,", extension=",f.name)},"register")})},unregister:function(f){this.extensions.splice(this.extensions.indexOf(f),1);this.handlers.forEach(function(i){i.unregister&&i.load(function(n){n?n(f):s.error("missing unregister function for pluginName=",
f.pluginName,", extension=",f.name)},"unregister")})},orderExtensions:function(f){for(var i=[],n=0;n<f.length;n++)for(var u=0;u!=this.extensions.length;)if(this.extensions[u].pluginName===f[n]){i.push(this.extensions[u]);this.extensions.splice(u,1)}else u++;this.extensions=i.concat(this.extensions)}};k.Plugin=function(f){this.name=this.catalog=null;this.provides=[];this.stylesheets=[];this.reloadPointer=this.reloadURL=null;for(property in f)if(f.hasOwnProperty(property))this[property]=f[property]};
k.Plugin.prototype={register:function(){this.provides.forEach(function(f){this.catalog.getExtensionPoint(f.ep,true).register(f)},this)},unregister:function(){this.provides.forEach(function(f){this.catalog.getExtensionPoint(f.ep,true).unregister(f)},this)},_getObservers:function(){var f={};this.provides.forEach(function(i){s.log("ep: ",i.ep);s.log(i._observers);f[i.ep]=i._observers});return f},_findDependents:function(f,i){var n=this.name,u=this;f.forEach(function(v){if(v!=n){var B=u.catalog.plugins[v];
if(B&&B.dependencies)for(dependName in B.dependencies)if(dependName==n&&!i[v]){i[v]={keepModule:false};B._findDependents(f,i)}}})},_cleanup:function(){this.stylesheets.forEach(function(B){for(var L=document.getElementsByTagName("link"),K=0;K<L.length;K++)if(L[K].href.indexOf(B.url)!=-1){L[K].parentNode.removeChild(L[K]);break}});var f=this.name,i=new RegExp("^"+f+"$"),n=new RegExp("^::"+f+":");f=new RegExp("^::"+f+"$");var u=A.sandbox,v=A.loader;w(n,v.factories);w(f,v.canonicalIds);w(f,v.canonicalPackageIds);
w(f,v.packageSources);w(f,v.packages);w(n,u.exports);w(n,u.modules);w(n,u.usedExports);w(i,o.packageInfoByName);w(n,o.factories);w(n,o.scriptActions);w(n,o.stylesheetActions);w(f,o.packages);w(f,o.ensureActions);w(f,o.packageInfoById)},reload:function(f){if(this.reloadURL){if(this.reloadPointer){var i=r(this.name,this.reloadPointer);if(func=D(i))func();else{s.error("Reload function could not be loaded. Aborting reload.");return}}var n={};this._findDependents(Object.keys(this.catalog.plugins),n);var u=
{pluginName:this.name,dependents:n};for(var v in n){i=this.catalog.plugins[v];if(i.preRefresh){i=r(v,i.preRefresh);if(func=D(i))n[v]=func(u)}}this.unregister();for(v in n)this.catalog.plugins[v].unregister();this._cleanup(this.name);i=[];var B=A.sandbox,L=Object.keys(B.modules),K=L.length,N=[];for(v in n)n[v].keepModule||N.push(new RegExp("^::"+v+":"));for(var T=new RegExp("^::"+this.name+":");--K>=0;){var g=L[K];if(T.exec(g))i.push(g);else for(var I=N.length;--I>=0;)if(N[I].exec(g)){i.push(g);break}}i.forEach(function(Q){delete B.exports[Q];
delete B.modules[Q];delete B.usedExports[Q]});i=function(){this.catalog.loadPlugin(this.name).then(function(){for(v in n)this.catalog.plugins[v].register();for(v in n)if(n[v].callPointer){var Q=r(v,n[v].callPointer);(Q=D(Q))&&Q(u)}f&&f()}.bind(this))}.bind(this);L=function(){s.error("Failed to load metadata from "+this.reloadURL)}.bind(this);this.catalog.loadMetadataFromURL(this.reloadURL).then(i,L)}}};var t=function(f,i,n){i=i.split(".");f=f;var u=i.length-1;if(u>0)for(var v=0;v<u;v++)f=f[i[v]];
f[u]=n};k.Catalog=function(){this.points={};this.plugins={};this.deactivatedPlugins={};this._extensionsOrdering=[];this.instances={};this.instancesLoadPromises={};this._objectDescriptors={};this.getExtensionPoint("extensionpoint",true).indexOn="name";this.loadMetadata(z.metadata)};k.Catalog.prototype={registerObject:function(f,i){this._objectDescriptors[f]=i},_setObject:function(f,i){this.instances[f]=i},createObject:function(f){if(this.instancesLoadPromises[f]!==undefined)return this.instancesLoadPromises[f];
var i=this.instancesLoadPromises[f]=new y,n=this._objectDescriptors[f];if(n===undefined)throw new Error('Tried to create object "'+f+'" but that object is not registered.');var u=n.factory||f,v=this.getExtensionByKey("factory",u);if(v===undefined)throw new Error('When creating object "'+f+'", there is no factory called "'+u+'" available."');var B=n.arguments||[];u=[];if(n.objects){n=n.objects;for(var L in n){var K=this.createObject(n[L]);u.push(K);K.location=L;K.then(function(N){t(B,K.location,N)})}}F(u).then(function(){v.load().then(function(N){var T=
v.action;if(T==="call")N=N.apply(N,B);else if(T==="new"){if(B.length>1){i.reject(new Error("For object "+f+", create a simple factory function and change the action to call because JS cannot handle this case."));return}N=new N(B[0])}else if(T==="value")N=N;else{i.reject(new Error("Create action must be call|new|value. Found"+T));return}this.instances[f]=N;i.resolve(N)}.bind(this))}.bind(this));return i},getObject:function(f){return this.instances[f]},getExtensionPoint:function(f,i){if(i&&this.points[f]===
undefined)this.points[f]=new k.ExtensionPoint(f,this);return this.points[f]},getExtensions:function(f){f=this.getExtensionPoint(f);if(f===undefined)return[];return f.extensions},orderExtensions:function(f){f=f||this._extensionsOrdering;for(name in this.points)this.points[name].orderExtensions(f);this._extensionsOrdering=f},getExtensionsOrdering:function(){return this._extensionsOrdering},getExtensionByKey:function(f,i){f=this.getExtensionPoint(f);if(f!==undefined)return f.getByKey(i)},_registerExtensionPoint:function(f){var i=
this.getExtensionPoint(f.name,true);i.description=f.description;i.pluginName=f.pluginName;i.params=f.params;if(f.indexOn)i.indexOn=f.indexOn;if(f.register||f.unregister)this._registerExtensionHandler(f)},_registerExtensionHandler:function(f){var i=this.getExtensionPoint(f.name,true);i.handlers.push(f);if(f.register){var n=h.clone(i.extensions);f.load(function(u){if(!u)throw f.name+" is not ready";n.forEach(function(v){u(v)})},"register")}},_toposort:function(f){var i=[],n={},u=function(B){if(!(B in
n||!(B in f))){n[B]=true;var L=f[B].dependencies;if(!h.none(L))for(var K in L)u(K);i.push(B)}};for(var v in f)u(v);return i},loadMetadata:function(f){var i=this.plugins,n;for(n in f)if(!this.deactivatedPlugins[n]){var u=f[n];if(u.errors){s.error("Plugin ",n," has errors:");u.errors.forEach(function(v){s.error(v)});delete f[n]}else{if(u.dependencies)u.depends=Object.keys(u.dependencies);u.name=n;u.version=null;o.canonicalPackageId(n)===null&&o.register("::"+n,u)}}this._toposort(f).forEach(function(v){var B=
f[v],L=!this.deactivatedPlugins[v];B.catalog=this;B.name=v;var K=new k.Plugin(B);i[v]=K;if(B.provides&&L){B=B.provides;for(L=0;L<B.length;L++){K=new k.Extension(B[L]);K.pluginName=v;B[L]=K;var N=K.ep;if(N=="extensionpoint")this._registerExtensionPoint(K);else N=="extensionhandler"&&this._registerExtensionHandler(K);this.getExtensionPoint(K.ep,true).register(K)}}else B.provides=[]},this);for(n in f)this._checkLoops(n,i,[]);this.orderExtensions()},loadPlugin:function(f){var i=new y,n=this.plugins[f];
if(n.objects){var u=[];n.objects.forEach(function(v){u.push(this.createObject(v))}.bind(this));F(u).then(function(){A.ensurePackage(f,function(){i.resolve()})})}else A.ensurePackage(f,function(){i.resolve()});return i},loadMetadataFromURL:function(f){var i=new y,n=new XMLHttpRequest;n.onreadystatechange=function(){if(n.readyState===4){var u=n.status;if(u!==0&&u!==200)i.reject("XHR error: "+n.statusText);else{this.loadMetadata(JSON.parse(n.responseText));i.resolve()}}}.bind(this);n.open("GET",f,true);
n.send();return i},deactivatePlugin:function(f){var i=this.plugins[f];if(i!==undefined){i.unregister();i._cleanup()}this.deactivatedPlugins[f]=true},removePlugin:function(f){var i=this.plugins[f];if(i==undefined)throw new Error("Attempted to remove plugin "+f+" which does not exist.");i.unregister();i._cleanup();delete this.plugins[f]},getResourceURL:function(f){var i=document.getElementById("bespin_base"),n="";if(i){n+=i.href;h.endsWith(n,"/")||(n+="/")}f=this.plugins[f];if(f!=undefined)return n+
f.resourceURL},_checkLoops:function(f,i,n){var u=false;n.forEach(function(L){if(f===L){s.error("Circular dependency",f,n);u=true}});if(u)return true;n.push(f);if(i[f]){if(i[f].dependencies)for(var v in i[f].dependencies){var B=n.slice();if(this._checkLoops(v,i,B)){s.error("Errors found when looking at ",f);return true}}}else s.error("Missing metadata for ",f);return false},getPlugins:function(f){var i=[],n=f.onlyType;for(var u in this.plugins){var v=this.plugins[u];n&&v.type&&v.type!=n||v.name=="bespin"||
i.push(v)}var B=f.sortBy;B||(B=["name"]);i.sort(function(L,K){for(var N=0;N<B.length;N++){u=B[N];if(L[u]<K[u])return-1;else if(K[u]<L[u])return 1}return 0});return i},loadObjectForPropertyPath:function(f,i){var n=new y,u=/^([^:]+):([^#]+)#(.*)$/.exec(f);if(u===null)throw new Error("loadObjectForPropertyPath: malformed path: '"+f+"'");u=u[1];if(u===""){if(h.none(i))throw new Error("loadObjectForPropertyPath: no plugin name supplied and no context is present");u=i}A.ensurePackage(u,function(){n.resolve(this.objectForPropertyPath(f))}.bind(this));
return n},objectForPropertyPath:function(f,i,n){n=n==undefined?f.length:n;i||(i=window);var u=f.split("#");if(u.length!==1){i=A(u[0]);if(i===undefined)return;f=u[1];i=i;n-=u[0].length}for(var v=0;i&&v<n;){u=f.indexOf(".",v);if(u<0||u>n)u=n;v=f.slice(v,u);i=i[v];v=u+1}if(v<n)i=undefined;return i},publish:function(f,i,n,u){this.getExtensions(i).forEach(function(v){if(v.match&&!v.regexp)v.regexp=new RegExp(v.match);if(v.regexp&&v.regexp.test(n)||v.key===n||h.none(v.key)&&h.none(n))v.load().then(function(B){B(f,
n,u)})})},registerExtension:function(f,i){i=new k.Extension(i);i.pluginName="__dynamic";this.getExtensionPoint(f).register(i)}};k.catalog=new k.Catalog;var w=function(f,i){for(var n=Object.keys(i),u=n.length;--u>0;)f.exec(n[u])&&delete i[n[u]]};k.getUserPlugins=function(){return k.catalog.getPlugins({onlyType:"user"})}});
bespin.tiki.module("bespin:promise",function(A,k){var y=A("bespin:console").console;A("bespin:util/stacktrace");var F=0;k._outstanding=[];k._recent=[];k.Promise=function(){this._status=0;this._value=undefined;this._onSuccessHandlers=[];this._onErrorHandlers=[];this._id=F++;k._outstanding[this._id]=this};k.Promise.prototype.isPromise=true;k.Promise.prototype.isComplete=function(){return this._status!=0};k.Promise.prototype.isResolved=function(){return this._status==1};k.Promise.prototype.isRejected=
function(){return this._status==-1};k.Promise.prototype.then=function(z,s){z!==null&&z!==undefined&&this._onSuccessHandlers.push(z);s!==null&&s!==undefined&&this._onErrorHandlers.push(s);this._status===1&&z.call(null,this._value);this._status===-1&&s.call(null,this._value);return this};k.Promise.prototype.chainPromise=function(z){var s=new k.Promise;s._chainedFrom=this;this.then(function(h){try{s.resolve(z(h))}catch(o){s.reject(o)}},function(h){s.reject(h)});return s};k.Promise.prototype.resolve=
function(z){return this._complete(this._onSuccessHandlers,1,z,"resolve")};k.Promise.prototype.reject=function(z){return this._complete(this._onErrorHandlers,-1,z,"reject")};k.Promise.prototype._complete=function(z,s,h,o){if(this._status!=0){y.group("Promise already closed");y.error("Attempted "+o+"() with ",h);y.error("Previous status = ",this._status,", previous value = ",this._value);y.trace();if(this._completeTrace){y.error("Trace of previous completion:");this._completeTrace.log(5)}y.groupEnd();
return this}this._status=s;this._value=h;z.forEach(function(r){r.call(null,this._value)},this);this._onSuccessHandlers.length=0;this._onErrorHandlers.length=0;delete k._outstanding[this._id];for(k._recent.push(this);k._recent.length>20;)k._recent.shift();return this};k.group=function(z){z instanceof Array||(z=Array.prototype.slice.call(arguments));if(z.length===0)return(new k.Promise).resolve([]);var s=new k.Promise,h=[],o=0,r=function(D){return function(t){h[D]=t;o++;s._status!==-1&&o===z.length&&
s.resolve(h)}};z.forEach(function(D,t){t=r(t);var w=s.reject.bind(s);D.then(t,w)});return s}});
bespin.tiki.module("bespin:util/cookie",function(A,k){var y=function(F,z){return F.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(s){if(z&&z.indexOf(s)!=-1)return s;return"\\"+s})};k.get=function(F){F=new RegExp("(?:^|; )"+y(F)+"=([^;]*)");return(F=document.cookie.match(F))?decodeURIComponent(F[1]):undefined};k.set=function(F,z,s){s=s||{};if(typeof s.expires=="number"){var h=new Date;h.setTime(h.getTime()+s.expires*24*60*60*1E3);s.expires=h}if(s.expires&&s.expires.toUTCString)s.expires=s.expires.toUTCString();
z=encodeURIComponent(z);F=F+"="+z;var o;for(o in s){F+="; "+o;z=s[o];if(z!==true)F+="="+z}document.cookie=F};k.remove=function(F){k.set(F,"",{expires:-1})};k.isSupported=function(){if(!("cookieEnabled"in navigator)){k.set("__djCookieTest__","CookiesAllowed");navigator.cookieEnabled=k.get("__djCookieTest__")=="CookiesAllowed";navigator.cookieEnabled&&k.remove("__djCookieTest__")}return navigator.cookieEnabled}});
bespin.tiki.module("bespin:util/scratchcanvas",function(A,k){var y=A("bespin:util/util"),F=function(){this._canvas=document.getElementById("bespin-scratch-canvas");if(y.none(this._canvas)){this._canvas=document.createElement("canvas");this._canvas.id="bespin-scratch-canvas";this._canvas.width=400;this._canvas.height=300;this._canvas.style.position="absolute";this._canvas.style.top="-10000px";this._canvas.style.left="-10000px";document.body.appendChild(this._canvas)}};F.prototype.getContext=function(){return this._canvas.getContext("2d")};
F.prototype.measureStringWidth=function(s,h){if(y.none(h))h="M";var o=this.getContext();o.save();o.font=s;s=o.measureText(h).width;o.restore();return s};var z=null;k.get=function(){if(z===null)z=new F;return z}});
bespin.tiki.module("bespin:util/stacktrace",function(A,k){function y(t){for(var w=0;w<t.length;++w){var f=t[w];if(typeof f=="object")t[w]="#object";else if(typeof f=="function")t[w]="#function";else if(typeof f=="string")t[w]='"'+f+'"'}return t.join(",")}function F(){}var z=A("bespin:util/util"),s=A("bespin:console").console,h=function(){if(z.isMozilla)return"firefox";else if(z.isOpera)return"opera";else if(z.isSafari)return"other";try{0()}catch(t){if(t.arguments)return"chrome";if(t.stack)return"firefox";
if(window.opera&&!("stacktrace"in t))return"opera"}return"other"}(),o={chrome:function(t){var w=t.stack;if(!w){s.log(t);return[]}return w.replace(/^.*?\n/,"").replace(/^.*?\n/,"").replace(/^.*?\n/,"").replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@").split("\n")},firefox:function(t){var w=t.stack;if(!w){s.log(t);return[]}w=w.replace(/(?:\n@:0)?\s+$/m,"");w=w.replace(/^\(/gm,"{anonymous}(");return w.split("\n")},opera:function(t){t=t.message.split("\n");
var w=/Line\s+(\d+).*?script\s+(http\S+)(?:.*?in\s+function\s+(\S+))?/i,f,i,n;f=4;i=0;for(n=t.length;f<n;f+=2)if(w.test(t[f]))t[i++]=(RegExp.$3?RegExp.$3+"()@"+RegExp.$2+RegExp.$1:"{anonymous}()@"+RegExp.$2+":"+RegExp.$1)+" -- "+t[f+1].replace(/^\s+/,"");t.splice(i,t.length-i);return t},other:function(t){for(var w=/function\s*([\w\-$]+)?\s*\(/i,f=[],i=0,n,u;t&&f.length<10;){n=w.test(t.toString())?RegExp.$1||"{anonymous}":"{anonymous}";u=Array.prototype.slice.call(t.arguments);f[i++]=n+"("+y(u)+")";
if(t===t.caller&&window.opera)break;t=t.caller}return f}};F.prototype={sourceCache:{},ajax:function(t){var w=this.createXMLHTTPObject();if(w){w.open("GET",t,false);w.setRequestHeader("User-Agent","XMLHTTP/1.0");w.send("");return w.responseText}},createXMLHTTPObject:function(){for(var t,w=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],f=0;f<
w.length;f++)try{t=w[f]();this.createXMLHTTPObject=w[f];return t}catch(i){}},getSource:function(t){t in this.sourceCache||(this.sourceCache[t]=this.ajax(t).split("\n"));return this.sourceCache[t]},guessFunctions:function(t){for(var w=0;w<t.length;++w){var f=t[w],i=/{anonymous}\(.*\)@(\w+:\/\/([-\w\.]+)+(:\d+)?[^:]+):(\d+):?(\d+)?/.exec(f);if(i){var n=i[1];i=i[4];if(n&&i){n=this.guessFunctionName(n,i);t[w]=f.replace("{anonymous}",n)}}}return t},guessFunctionName:function(t,w){try{return this.guessFunctionNameFromLines(w,
this.getSource(t))}catch(f){return"getSource failed with url: "+t+", exception: "+f.toString()}},guessFunctionNameFromLines:function(t,w){for(var f=/function ([^(]*)\(([^)]*)\)/,i=/['"]?([0-9A-Za-z_]+)['"]?\s*[:=]\s*(function|eval|new Function)/,n="",u=0;u<10;++u){n=w[t-u]+n;if(n!==undefined){var v=i.exec(n);if(v)return v[1];else v=f.exec(n);if(v&&v[1])return v[1]}}return"(?)"}};var r=new F,D=[/http:\/\/localhost:4020\/sproutcore.js:/];k.ignoreFramesMatching=function(t){D.push(t)};k.Trace=function(t,
w){this._ex=t;this._stack=o[h](t);if(w)this._stack=r.guessFunctions(this._stack)};k.Trace.prototype.log=function(t){if(t<=0)t=999999999;for(var w=0,f=0;f<this._stack.length&&w<t;f++){var i=this._stack[f],n=true;D.forEach(function(u){if(u.test(i))n=false});if(n){s.debug(i);w++}}}});
bespin.tiki.module("bespin:util/util",function(A,k){k.queryToObject=function(h,o){var r={};h=h.split(o||"&");var D=decodeURIComponent;h.forEach(function(t){if(t.length){var w=t.split("=");t=D(w.shift());w=D(w.join("="));if(k.isString(r[t]))r[t]=[r[t]];if(Array.isArray(r[t]))r[t].push(w);else r[t]=w}});return r};k.objectToQuery=function(h){var o=encodeURIComponent,r=[],D={};for(var t in h){var w=h[t];if(w!=D[t]){var f=o(t)+"=";if(w.isArray)for(var i=0;i<w.length;i++)r.push(f+o(w[i]));else r.push(f+
o(w))}}return r.join("&")};var y=0,F={};k.rateLimit=function(h,o,r){if(h){var D=y++;return function(){F[D]&&clearTimeout(F[D]);F[D]=setTimeout(function(){r.apply(o,arguments);delete F[D]},h)}}};k.isString=function(h){return typeof h=="string"||h instanceof String};k.isBoolean=function(h){return typeof h=="boolean"};k.isNumber=function(h){return typeof h=="number"&&isFinite(h)};k.isObject=function(h){return h!==undefined&&(h===null||typeof h=="object"||Array.isArray(h)||k.isFunction(h))};k.isFunction=
function(){var h=function(o){var r=typeof o;return o&&(r=="function"||o instanceof Function)&&!o.nodeType};return k.isSafari?function(o){if(typeof o=="function"&&o=="[object NodeList]")return false;return h(o)}:h}();k.endsWith=function(h,o){if(!h)return false;return h.match(new RegExp(o+"$"))};k.include=function(h,o){return h.indexOf(o)>-1};k.indexOfProperty=function(h,o,r){for(var D=0;D<h.length;D++)if(h[D][o]==r)return D;return null};k.last=function(h){if(Array.isArray(h))return h[h.length-1]};
k.shrinkArray=function(h){var o=[],r=true;h.reverse().forEach(function(D){if(!(r&&D===undefined)){r=false;o.push(D)}});return o.reverse()};k.makeArray=function(h,o){if(h<1)return[];o||(o=" ");for(var r=[],D=0;D<h;D++)r.push(o);return r};k.repeatString=function(h,o){for(var r="",D=0;D<o;D++)r+=h;return r};k.leadingSpaces=function(h){for(var o=0,r=0;r<h.length;r++)if(h[r]==" "||h[r]==""||h[r]===undefined)o++;else return o;return o};k.leadingTabs=function(h){for(var o=0,r=0;r<h.length;r++)if(h[r]=="\t"||
h[r]==""||h[r]===undefined)o++;else return o;return o};k.leadingWhitespace=function(h){for(var o=[],r=0;r<h.length;r++)if(h[r]==" "||h[r]=="\t"||h[r]==""||h[r]===undefined)o.push(h[r]);else return o;return o};k.englishFromCamel=function(h){h.replace(/([A-Z])/g,function(o){return" "+o.toLowerCase()}).trim()};k.OS={LINUX:"LINUX",MAC:"MAC",WINDOWS:"WINDOWS"};A=navigator.userAgent;var z=navigator.appVersion;k.isLinux=z.indexOf("Linux")>=0;k.isWindows=z.indexOf("Win")>=0;k.isWebKit=parseFloat(A.split("WebKit/")[1])||
undefined;k.isChrome=parseFloat(A.split("Chrome/")[1])||undefined;k.isMac=z.indexOf("Macintosh")>=0;k.isMozilla=z.indexOf("Gecko/")>=0;if(A.indexOf("AdobeAIR")>=0)k.isAIR=1;var s=Math.max(z.indexOf("WebKit"),z.indexOf("Safari"),0);if(s&&!k.isChrome){k.isSafari=parseFloat(z.split("Version/")[1]);if(!k.isSafari||parseFloat(z.substr(s+7))<=419.3)k.isSafari=2}if(A.indexOf("Gecko")>=0&&!k.isWebKit)k.isMozilla=parseFloat(z);k.getOS=function(){return k.isMac?k.OS.MAC:k.isLinux?k.OS.LINUX:k.OS.WINDOWS};k.contains=
typeof document!=="undefined"&&document.compareDocumentPosition?function(h,o){return h.compareDocumentPosition(o)&16}:function(h,o){return h!==o&&(h.contains?h.contains(o):true)};k.stopEvent=function(h){h.preventDefault();h.stopPropagation()};k.randomPassword=function(h){h=h||16;for(var o="",r=0;r<h;r++){var D=Math.floor(Math.random()*62);o+="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890".charAt(D)}return o};k.isEmpty=function(h){for(var o in h)if(h.hasOwnProperty(o))return false;
return true};k.isMyProject=function(h){return h.indexOf("+")==-1};k.formatDate=function(h){if(!h)return"Unknown";return h.getDate()+" "+k.formatDate.shortMonths[h.getMonth()]+" "+h.getFullYear()};k.formatDate.shortMonths=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];k.addClass=function(h,o){o=o.split(/\s+/);for(var r=" "+h.className+" ",D=0,t=o.length,w;D<t;++D)if((w=o[D])&&r.indexOf(" "+w+" ")<0)r+=w+" ";h.className=r.trim()};k.removeClass=function(h,o){if(o!==undefined){var r=
o.split(/\s+/);o=" "+h.className+" ";for(var D=0,t=r.length;D<t;++D)o=o.replace(" "+r[D]+" "," ");o=o.trim()}else o="";if(h.className!=o)h.className=o};k.setClass=function(h,o,r){r?k.addClass(h,o):k.removeClass(h,o)};k.none=function(h){return h===null||h===undefined};k.clone=function(h){if(Array.isArray(h))return h.slice();if(typeof h==="object"){if(h===null)return null;var o={};for(var r in h)o[r]=h[r];return o}if(h.clone&&typeof h.clone==="function")return h.clone();return h};k.mixin=function(h,
o){for(var r in o){var D=o.__lookupGetter__(r),t=o.__lookupSetter__(r);if(D||t){D&&h.__defineGetter__(r,D);t&&h.__defineSetter__(r,t)}else h[r]=o[r]}return h};k.replace=function(h,o,r,D){return h.slice(0,o).concat(D).concat(h.slice(o+r))};k.rectsEqual=function(h,o,r){if(!h||!o)return h==o;if(!r&&r!==0)r=0.1;if(h.y!=o.y&&Math.abs(h.y-o.y)>r)return false;if(h.x!=o.x&&Math.abs(h.x-o.x)>r)return false;if(h.width!=o.width&&Math.abs(h.width-o.width)>r)return false;if(h.height!=o.height&&Math.abs(h.height-
o.height)>r)return false;return true}});bespin.tiki.register("::syntax_directory",{name:"syntax_directory",dependencies:{}});
bespin.tiki.module("syntax_directory:index",function(A,k){function y(s){this.extension=s;this.name=s.name;this.fileExts=s.hasOwnProperty("fileexts")?s.fileexts:[]}function F(s){z.register(s)}A("bespin:plugins");var z={_fileExts:{},_syntaxInfo:{},get:function(s){return this._syntaxInfo[s]},hasSyntax:function(s){return this._syntaxInfo.hasOwnProperty(s)},register:function(s){var h=new y(s);this._syntaxInfo[h.name]=h;var o=this._fileExts;h.fileExts.forEach(function(r){o[r]=h.name})},syntaxForFileExt:function(s){s=
s.toLowerCase();var h=this._fileExts;return h.hasOwnProperty(s)?h[s]:"plain"}};k.syntaxDirectory=z;k.discoveredNewSyntax=F});bespin.tiki.register("::underscore",{name:"underscore",dependencies:{}});
bespin.tiki.module("underscore:index",function(A,k){(function(){var y=this,F=y._,z=typeof StopIteration!=="undefined"?StopIteration:"__break__",s=function(e){return e.replace(/([.*+?^${}()|[\]\/\\])/g,"\\$1")},h=Array.prototype,o=Object.prototype,r=h.slice,D=h.unshift,t=o.toString,w=o.hasOwnProperty,f=h.forEach,i=h.map,n=h.reduce,u=h.reduceRight,v=h.filter,B=h.every,L=h.some,K=h.indexOf,N=h.lastIndexOf;o=Array.isArray;var T=Object.keys,g=function(e){return new U(e)};if(typeof k!=="undefined")k._=
g;y._=g;g.VERSION="1.0.2";var I=g.forEach=function(e,j,q){try{if(f&&e.forEach===f)e.forEach(j,q);else if(g.isNumber(e.length))for(var p=0,E=e.length;p<E;p++)j.call(q,e[p],p,e);else for(p in e)w.call(e,p)&&j.call(q,e[p],p,e)}catch(H){if(H!=z)throw H;}return e};g.map=function(e,j,q){if(i&&e.map===i)return e.map(j,q);var p=[];I(e,function(E,H,O){p.push(j.call(q,E,H,O))});return p};g.reduce=function(e,j,q,p){if(n&&e.reduce===n)return e.reduce(g.bind(q,p),j);I(e,function(E,H,O){j=q.call(p,j,E,H,O)});return j};
g.reduceRight=function(e,j,q,p){if(u&&e.reduceRight===u)return e.reduceRight(g.bind(q,p),j);e=g.clone(g.toArray(e)).reverse();return g.reduce(e,j,q,p)};g.detect=function(e,j,q){var p;I(e,function(E,H,O){if(j.call(q,E,H,O)){p=E;g.breakLoop()}});return p};g.filter=function(e,j,q){if(v&&e.filter===v)return e.filter(j,q);var p=[];I(e,function(E,H,O){j.call(q,E,H,O)&&p.push(E)});return p};g.reject=function(e,j,q){var p=[];I(e,function(E,H,O){!j.call(q,E,H,O)&&p.push(E)});return p};g.every=function(e,j,
q){j=j||g.identity;if(B&&e.every===B)return e.every(j,q);var p=true;I(e,function(E,H,O){(p=p&&j.call(q,E,H,O))||g.breakLoop()});return p};g.some=function(e,j,q){j=j||g.identity;if(L&&e.some===L)return e.some(j,q);var p=false;I(e,function(E,H,O){if(p=j.call(q,E,H,O))g.breakLoop()});return p};g.include=function(e,j){if(K&&e.indexOf===K)return e.indexOf(j)!=-1;var q=false;I(e,function(p){if(q=p===j)g.breakLoop()});return q};g.invoke=function(e,j){var q=g.rest(arguments,2);return g.map(e,function(p){return(j?
p[j]:p).apply(p,q)})};g.pluck=function(e,j){return g.map(e,function(q){return q[j]})};g.max=function(e,j,q){if(!j&&g.isArray(e))return Math.max.apply(Math,e);var p={computed:-Infinity};I(e,function(E,H,O){H=j?j.call(q,E,H,O):E;H>=p.computed&&(p={value:E,computed:H})});return p.value};g.min=function(e,j,q){if(!j&&g.isArray(e))return Math.min.apply(Math,e);var p={computed:Infinity};I(e,function(E,H,O){H=j?j.call(q,E,H,O):E;H<p.computed&&(p={value:E,computed:H})});return p.value};g.sortBy=function(e,
j,q){return g.pluck(g.map(e,function(p,E,H){return{value:p,criteria:j.call(q,p,E,H)}}).sort(function(p,E){p=p.criteria;E=E.criteria;return p<E?-1:p>E?1:0}),"value")};g.sortedIndex=function(e,j,q){q=q||g.identity;for(var p=0,E=e.length;p<E;){var H=p+E>>1;q(e[H])<q(j)?(p=H+1):(E=H)}return p};g.toArray=function(e){if(!e)return[];if(e.toArray)return e.toArray();if(g.isArray(e))return e;if(g.isArguments(e))return r.call(e);return g.values(e)};g.size=function(e){return g.toArray(e).length};g.first=function(e,
j,q){return j&&!q?r.call(e,0,j):e[0]};g.rest=function(e,j,q){return r.call(e,g.isUndefined(j)||q?1:j)};g.last=function(e){return e[e.length-1]};g.compact=function(e){return g.filter(e,function(j){return!!j})};g.flatten=function(e){return g.reduce(e,[],function(j,q){if(g.isArray(q))return j.concat(g.flatten(q));j.push(q);return j})};g.without=function(e){var j=g.rest(arguments);return g.filter(e,function(q){return!g.include(j,q)})};g.uniq=function(e,j){return g.reduce(e,[],function(q,p,E){if(0==E||
(j===true?g.last(q)!=p:!g.include(q,p)))q.push(p);return q})};g.intersect=function(e){var j=g.rest(arguments);return g.filter(g.uniq(e),function(q){return g.every(j,function(p){return g.indexOf(p,q)>=0})})};g.zip=function(){for(var e=g.toArray(arguments),j=g.max(g.pluck(e,"length")),q=new Array(j),p=0;p<j;p++)q[p]=g.pluck(e,String(p));return q};g.indexOf=function(e,j){if(K&&e.indexOf===K)return e.indexOf(j);for(var q=0,p=e.length;q<p;q++)if(e[q]===j)return q;return-1};g.lastIndexOf=function(e,j){if(N&&
e.lastIndexOf===N)return e.lastIndexOf(j);for(var q=e.length;q--;)if(e[q]===j)return q;return-1};g.range=function(e,j,q){var p=g.toArray(arguments),E=p.length<=1;e=E?0:p[0];j=E?p[0]:p[1];q=p[2]||1;p=Math.ceil((j-e)/q);if(p<=0)return[];p=new Array(p);E=e;for(var H=0;;E+=q){if((q>0?E-j:j-E)>=0)return p;p[H++]=E}};g.bind=function(e,j){var q=g.rest(arguments,2);return function(){return e.apply(j||{},q.concat(g.toArray(arguments)))}};g.bindAll=function(e){var j=g.rest(arguments);if(j.length==0)j=g.functions(e);
I(j,function(q){e[q]=g.bind(e[q],e)});return e};g.delay=function(e,j){var q=g.rest(arguments,2);return setTimeout(function(){return e.apply(e,q)},j)};g.defer=function(e){return g.delay.apply(g,[e,1].concat(g.rest(arguments)))};g.wrap=function(e,j){return function(){var q=[e].concat(g.toArray(arguments));return j.apply(j,q)}};g.compose=function(){var e=g.toArray(arguments);return function(){for(var j=g.toArray(arguments),q=e.length-1;q>=0;q--)j=[e[q].apply(this,j)];return j[0]}};g.keys=T||function(e){if(g.isArray(e))return g.range(0,
e.length);var j=[];for(var q in e)w.call(e,q)&&j.push(q);return j};g.values=function(e){return g.map(e,g.identity)};g.functions=function(e){return g.filter(g.keys(e),function(j){return g.isFunction(e[j])}).sort()};g.extend=function(e){I(g.rest(arguments),function(j){for(var q in j)e[q]=j[q]});return e};g.clone=function(e){if(g.isArray(e))return e.slice(0);return g.extend({},e)};g.tap=function(e,j){j(e);return e};g.isEqual=function(e,j){if(e===j)return true;var q=typeof e;if(q!=typeof j)return false;
if(e==j)return true;if(!e&&j||e&&!j)return false;if(e.isEqual)return e.isEqual(j);if(g.isDate(e)&&g.isDate(j))return e.getTime()===j.getTime();if(g.isNaN(e)&&g.isNaN(j))return true;if(g.isRegExp(e)&&g.isRegExp(j))return e.source===j.source&&e.global===j.global&&e.ignoreCase===j.ignoreCase&&e.multiline===j.multiline;if(q!=="object")return false;if(e.length&&e.length!==j.length)return false;q=g.keys(e);var p=g.keys(j);if(q.length!=p.length)return false;for(var E in e)if(!(E in j)||!g.isEqual(e[E],j[E]))return false;
return true};g.isEmpty=function(e){if(g.isArray(e)||g.isString(e))return e.length===0;for(var j in e)if(w.call(e,j))return false;return true};g.isElement=function(e){return!!(e&&e.nodeType==1)};g.isArray=o||function(e){return!!(e&&e.concat&&e.unshift&&!e.callee)};g.isArguments=function(e){return e&&e.callee};g.isFunction=function(e){return!!(e&&e.constructor&&e.call&&e.apply)};g.isString=function(e){return!!(e===""||e&&e.charCodeAt&&e.substr)};g.isNumber=function(e){return e===+e||t.call(e)==="[object Number]"};
g.isBoolean=function(e){return e===true||e===false};g.isDate=function(e){return!!(e&&e.getTimezoneOffset&&e.setUTCFullYear)};g.isRegExp=function(e){return!!(e&&e.test&&e.exec&&(e.ignoreCase||e.ignoreCase===false))};g.isNaN=function(e){return g.isNumber(e)&&isNaN(e)};g.isNull=function(e){return e===null};g.isUndefined=function(e){return typeof e=="undefined"};g.noConflict=function(){y._=F;return this};g.identity=function(e){return e};g.times=function(e,j,q){for(var p=0;p<e;p++)j.call(q,p)};g.breakLoop=
function(){throw z;};g.mixin=function(e){I(g.functions(e),function(j){P(j,g[j]=e[j])})};var Q=0;g.uniqueId=function(e){var j=Q++;return e?e+j:j};g.templateSettings={start:"<%",end:"%>",interpolate:/<%=(.+?)%>/g};g.template=function(e,j){var q=g.templateSettings,p=new RegExp("'(?=[^"+q.end.substr(0,1)+"]*"+s(q.end)+")","g");e=new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+e.replace(/[\r\t\n]/g," ").replace(p,"\t").split("'").join("\\'").split("\t").join("'").replace(q.interpolate,
"',$1,'").split(q.start).join("');").split(q.end).join("p.push('")+"');}return p.join('');");return j?e(j):e};g.each=g.forEach;g.foldl=g.inject=g.reduce;g.foldr=g.reduceRight;g.select=g.filter;g.all=g.every;g.any=g.some;g.head=g.first;g.tail=g.rest;g.methods=g.functions;var U=function(e){this._wrapped=e},R=function(e,j){return j?g(e).chain():e},P=function(e,j){U.prototype[e]=function(){var q=g.toArray(arguments);D.call(q,this._wrapped);return R(j.apply(g,q),this._chain)}};g.mixin(g);I(["pop","push",
"reverse","shift","sort","splice","unshift"],function(e){var j=h[e];U.prototype[e]=function(){j.apply(this._wrapped,arguments);return R(this._wrapped,this._chain)}});I(["concat","join","slice"],function(e){var j=h[e];U.prototype[e]=function(){return R(j.apply(this._wrapped,arguments),this._chain)}});U.prototype.chain=function(){this._chain=true;return this};U.prototype.value=function(){return this._wrapped}})();k._.noConflict()});
bespin.tiki.require("bespin:plugins").catalog.loadMetadata({jquery:{testmodules:[],resourceURL:"resources/jquery/",name:"globaljquery",type:"thirdparty"},bespin:{resourceURL:"resources/bespin/",name:"bespin",environments:{main:true,worker:true},dependencies:{jquery:"1.4.0"},testmodules:[],type:"plugins\\boot"},syntax_directory:{resourceURL:"resources/syntax_directory/",name:"syntax_directory",environments:{main:true,worker:true},dependencies:{},testmodules:[],provides:[{register:"#discoveredNewSyntax",
ep:"extensionhandler",name:"syntax"}],type:"plugins\\supported",description:"Catalogs the available syntax engines"},underscore:{testmodules:[],type:"plugins\\thirdparty",resourceURL:"resources/underscore/",description:"Functional Programming Aid for Javascript. Works well with jQuery.",name:"underscore"}});typeof window==="undefined"?importScripts("BespinWorker.js"):function(){var A=document.createElement("script");A.setAttribute("src",bespin.base+"BespinMain.js");document.getElementsByTagName("head")[0].appendChild(A)}();
