bespin.tiki.register("::javascript",{name:"javascript",dependencies:{standard_syntax:"0.0.0"}});
bespin.tiki.module("javascript:index",function(a,d){a("bespin:promise");a=a("standard_syntax").StandardSyntax;d.JSSyntax=new a({start:[{regex:/^(?:break|case|catch|continue|default|delete|do|else|false|finally|for|function|if|in|instanceof|let|new|null|return|switch|this|throw|true|try|typeof|var|void|while|with)(?![a-zA-Z0-9_])/,tag:"keyword"},{regex:/^[A-Za-z_][A-Za-z0-9_]*/,tag:"plain"},{regex:/^[^'"\/ \tA-Za-z0-9_]+/,tag:"plain"},{regex:/^[ \t]+/,tag:"plain"},{regex:/^'/,tag:"string",then:"qstring"},
{regex:/^"/,tag:"string",then:"qqstring"},{regex:/^\/\/.*/,tag:"comment"},{regex:/^\/\*/,tag:"comment",then:"comment"},{regex:/^./,tag:"plain"}],qstring:[{regex:/^'/,tag:"string",then:"start"},{regex:/^(?:\\.|[^'\\])+/,tag:"string"}],qqstring:[{regex:/^"/,tag:"string",then:"start"},{regex:/^(?:\\.|[^"\\])+/,tag:"string"}],comment:[{regex:/^[^*\/]+/,tag:"comment"},{regex:/^\*\//,tag:"comment",then:"start"},{regex:/^[*\/]/,tag:"comment"}]})});
bespin.tiki.register("::syntax_worker",{name:"syntax_worker",dependencies:{syntax_directory:"0.0.0",underscore:"0.0.0"}});
bespin.tiki.module("syntax_worker:index",function(a,d){var g=a("bespin:promise"),b=a("underscore")._;a("bespin:console");var c=a("syntax_directory").syntaxDirectory;d.syntaxWorker={engines:{},annotate:function(h,j){function m(e){return e.split(":")}function o(){p.push(b(f).invoke("join",":").join(" "))}var i=this.engines,p=[],k=[],f=b(h.split(" ")).map(m);b(j).each(function(e){o();for(var r=[],l=0;l<e.length;){for(var q;;){q=b(f).last();if(q.length<3)break;var n=q[2];if(e.substring(l,l+n.length)!==
n)break;f.pop()}n=i[q[0]].get(q,e,l);if(n==null)l={state:"plain",tag:"plain",start:l,end:e.length};else{f[f.length-1]=n.state;n.hasOwnProperty("newContext")&&f.push(n.newContext);l=n.token}r.push(l);l=l.end}k.push(r)});o();return{states:p,attrs:k}},loadSyntax:function(h){var j=new g.Promise,m=this.engines;if(m.hasOwnProperty(h)){j.resolve();return j}var o=c.get(h);if(o==null)throw new Error('No syntax engine installed for syntax "'+h+'".');o.extension.load().then(function(i){m[h]=i;i=i.subsyntaxes;
i==null?j.resolve():g.group(b(i).map(this.loadSyntax,this)).then(b(j.resolve).bind(j))}.bind(this));return j}}});bespin.tiki.register("::standard_syntax",{name:"standard_syntax",dependencies:{syntax_worker:"0.0.0",syntax_directory:"0.0.0",underscore:"0.0.0"}});
bespin.tiki.module("standard_syntax:index",function(a,d){a("bespin:promise");var g=a("underscore")._;a("bespin:console");a("syntax_directory");d.StandardSyntax=function(b,c){this.states=b;this.subsyntaxes=c};d.StandardSyntax.prototype={get:function(b,c,h){var j=b[0],m=b[1];if(!this.states.hasOwnProperty(m))throw new Error('StandardSyntax: no such state "'+m+'"');var o=c.substring(h),i={start:h,state:b},p=null;g(this.states[m]).each(function(k){var f=k.regex.exec(o);if(f!=null){var e=f[0].length;i.end=
h+e;i.tag=k.tag;f=null;if(k.hasOwnProperty("then")){e=k.then.split(" ");k=[j,e[0]];if(e.length>1)f=e[1].split(":")}else if(e===0)throw new Error("StandardSyntax: Infinite loop detected: zero-length match that didn't change state");else k=b;p={state:k,token:i};if(f!=null)p.newContext=f;g.breakLoop()}});return p}}});
bespin.metadata={standard_syntax:{resourceURL:"resources/standard_syntax/",description:"Easy-to-use basis for syntax engines",environments:{worker:true},dependencies:{syntax_worker:"0.0.0",syntax_directory:"0.0.0",underscore:"0.0.0"},testmodules:[],type:"plugins\\supported",name:"standard_syntax"},javascript:{resourceURL:"resources/javascript/",name:"javascript",environments:{worker:true},dependencies:{standard_syntax:"0.0.0"},testmodules:[],provides:[{pointer:"#JSSyntax",ep:"syntax",fileexts:["js",
"json"],name:"js"}],type:"plugins\\supported",description:"JavaScript syntax highlighter"},syntax_worker:{resourceURL:"resources/syntax_worker/",description:"Coordinates multiple syntax engines",environments:{worker:true},dependencies:{syntax_directory:"0.0.0",underscore:"0.0.0"},testmodules:[],type:"plugins\\supported",name:"syntax_worker"}};
if(typeof window!=="undefined")throw new Error('"worker.js can only be loaded in a web worker. Use the "worker_manager" plugin to instantiate web workers.');var messageQueue=[],target=null;if(typeof bespin==="undefined")bespin={};
function pump(){if(messageQueue.length!==0){var a=messageQueue[0];switch(a.op){case "load":var d=a.base;bespin.base=d;bespin.hasOwnProperty("tiki")||importScripts(d+"tiki.js");if(!bespin.bootLoaded){importScripts(d+"plugin/register/boot");bespin.bootLoaded=true}var g=bespin.tiki.require;g.loader.sources[0].xhr=true;g.ensurePackage("::bespin",function(){var c=g("bespin:plugins").catalog,h=g("bespin:promise").Promise;if(bespin.hasOwnProperty("metadata")){c.loadMetadata(bespin.metadata);c=new h;c.resolve()}else c=
c.loadMetadataFromURL("plugin/register/worker");c.then(function(){g.ensurePackage(a.pkg,function(){target=g(a.module)[a.target];messageQueue.shift();pump()})})});break;case "invoke":d=function(c){postMessage(JSON.stringify({op:"finish",id:a.id,result:c}));messageQueue.shift();pump()};if(!target.hasOwnProperty(a.method))throw new Error("No such method: "+a.method);var b=target[a.method].apply(target,a.args);typeof b==="object"&&b.isPromise?b.then(d,function(c){throw c;}):d(b);break}}}
onmessage=function(a){messageQueue.push(JSON.parse(a.data));messageQueue.length===1&&pump()};
